version: '3.9'

services:
  postgres:
    image: timescale/timescaledb:latest-pg14
    container_name: rms-property-service-pgsql-database
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      retries: 5
      start_period: 10s

  service-property:
    build: .
    env_file:
      - .env
    image: realty-management-system-property-service
    container_name: realty-management-property-service
    depends_on:
      - postgres
    ports:
      - "8082:8082"

volumes:
  postgres_storage:
