
CREATE TABLE properties (
    property_uuid UUID NOT NULL,
    agent_uuid UUID NOT NULL,
    region_id INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    deal_type VARCHAR(255) NOT NULL,
    price DECIMAL NOT NULL,
    rooms INTEGER NOT NULL,
    area DECIMAL NOT NULL,
    address VARCHAR(255) NOT NULL,
    description TEXT,
    layout VARCHAR(255) NOT NULL,
    latitude DECIMAL NOT NULL,
    longitude DECIMAL NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    owner_name VARCHAR(255),
    owner_surname VARCHAR(255),
    owner_phone VARCHAR(255),
    paid BOOL NOT NULL,
    PRIMARY KEY(property_uuid)
);


CREATE TABLE features (
    feature_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE,
    PRIMARY KEY(feature_id)
);


CREATE TABLE properties_to_features (
    property_uuid UUID NOT NULL,
    feature_id INTEGER NOT NULL,
    PRIMARY KEY(property_uuid, feature_id),
    FOREIGN KEY (property_uuid) REFERENCES properties(property_uuid) ON UPDATE NO ACTION ON DELETE CASCADE,
    FOREIGN KEY (feature_id) REFERENCES features(feature_id) ON UPDATE NO ACTION ON DELETE CASCADE
);


CREATE TABLE property_images_metadata (
    image_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    property_uuid UUID NOT NULL,
    file_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY(image_id),
    FOREIGN KEY (property_uuid) REFERENCES properties(property_uuid) ON UPDATE NO ACTION ON DELETE CASCADE
);


CREATE TABLE calendar (
    calendar_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    property_uuid UUID NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    user_uuid UUID,
    status VARCHAR(255) NOT NULL,
    PRIMARY KEY(calendar_id),
    FOREIGN KEY (property_uuid) REFERENCES properties(property_uuid) ON UPDATE NO ACTION ON DELETE CASCADE
);
